#!/usr/bin/env sh

signal() {
	xsetroot -name "fsignal:$*"
}

case $# in
1)
	case $1 in
	restart)
		signal $1
		;;
	*)
		echo "Unknown command or missing one argument."
		exit 1
		;;
	esac
	;;
2)
	case $1 in
	viewex)
		signal $1 i $2
		;;
	*)
		echo "Unknown command or one too many arguments."
		exit 1
		;;
	esac
	;;
*)
	echo "Too many arguments."
	exit 1
	;;
esac
