#!/bin/bash

# Prints out the time

CHARGING_ICON=''
WARNING_ICON=''

ICON="%"

WIFI_FULL_ICON='󰤨'
WIFI_HIGH_ICON='󰤥'
WIFI_MID_ICON='󰤢'
WIFI_LOW_ICON='󰤟'
NO_WIFI_ICON='󰤮'

WIFI=' '
VOLUME=""

get_main()
{
  if grep -q wl* "/proc/net/wireless"; then
      # Wifi quality percentage
      percentage=$(grep "^\s*w" /proc/net/wireless | awk '{ print "", int($3 * 100 / 70)}'| xargs)
      case $percentage in
         0)                              WIFI="$NO_WIFI_ICON";;
         100|9[0-9]|8[0-9])       WIFI="$WIFI_FULL_ICON" ;;
         7[0-9]|6[0-9]|5[0-9])    WIFI="$WIFI_HIGH_ICON" ;;
         4[0-9]|3[0-9])    WIFI="$WIFI_MID_ICON" ;;
         2[0-9]|1[0-9]|[0-9])            WIFI="$WIFI_LOW_ICON" ;;
      esac
    fi

    if [ -f /tmp/dwmbar_volume ] && [ $(cat /tmp/dwmbar_volume) = 1 ]; then
      VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | tail -n 2 | sed -e 's,.* \([0-9][0-9]*\)%.*,󰕾 \1% ,' | head -n 1)
    else
      VOLUME='' 
    fi

    if [ -d /sys/class/power_supply/BAT0 ]; then
		capacity=$(cat /sys/class/power_supply/BAT0/capacity)
		charging=$(cat /sys/class/power_supply/BAT0/status)

		if [[ "$charging" == "Charging" ]]; then
			ICON="$CHARGING_ICON"
		elif [[ $capacity -le 15 ]]; then
			ICON="$WARNING_ICON"
		fi
	fi
    # there is a thin space after wifi
    echo "$VOLUME$capacity$ICON $WIFI  $(date '+%H:%M')"
}

get_main
