backend = "xrender";

animations = ({
    triggers = [ "open", "show" ];
    scale-x = {
        curve = "cubic-bezier(0.175, 0.885, 0.32, 1.0)";
        duration = 0.16;
        delay = 0;
        start = 0.8;
        end = 1;
    };
    offset-x = {
        curve = "cubic-bezier(0.175, 0.885, 0.32, 1.0)";
        duration = 0.16;
        delay = 0;
        start = "window-width / 6.4";
        end = 0;
    }
    scale-y = {
        curve = "cubic-bezier(0.175, 0.885, 0.32, 1.0)";
        duration = 0.16;
        delay = 0;
        start = 0.8;
        end = 1;
    };
    offset-y = {
        curve = "cubic-bezier(0.175, 0.885, 0.32, 1.0)";
        duration = 0.16;
        delay = 0;
        start = "window-height / 6.4";
        end = 0;
    };
    opacity = {
        curve = "cubic-bezier(0.175, 0.885, 0.32, 1.0)";
        duration = 0.16;
        start = 0.1;
        end = 1;
    }
}, {
    triggers = [ "close", "hide" ];
    preset = "disappear";
    scale = 0.9;
    duration = 0.18;
}, 
);

rules = (
    { match = "class_g = 'dwm'"; 
      animations = ({
          triggers = ["geometry", "hide", "show", "close", "open"];
          duration: 0;
      });
    },
)
